cls
del EBCGOPTEST.EFI, EBCGOPTEST.TMP
C:\Work\Fasm_Editor_Debugger\WinFasm17149\fasm asm\EBCGOPTEST.ASM EBCGOPTEST.TMP
ebcpatch32 EBCGOPTEST.TMP EBCGOPTEST.EFI
comp EBCGOPTEST.TMP EBCGOPTEST.EFI
del EBCGOPTEST.TMP


