;===========================================================================;
;=                                                                         =;
;=                       PROGRAM AND VENDOR DATA.                          =;
;=                                                                         =;
;===========================================================================;

String_Version		DB  'Graphics Output Protocol.Block Transfer sample for EFI Byte Code.',0
String_Copyright	DB  '(C) IC Book Labs.',0
String_Http		DB  'http://jelezo.com.ua/' , 0

