;===========================================================================;
;=                                                                         =;
;=               DATA FOR BUILT SYSTEM INFORMATION STRING.                 =;
;=                                                                         =;
;===========================================================================;

;--- Text strings ---

String_Video_Mode	DB  'GOP video mode = '
String_Video_Mode_1	DB  16 DUP (0)

String_Xsize		DB  'Xsize = '
String_Xsize_1		DB  16 DUP (0)

String_Ysize		DB  'Ysize = '
String_Ysize_1		DB  16 DUP (0)


